version: '3'

services:
  server_server:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOME}/docker_serv_az/:/log
      - ./log:/log
    container_name: server-server
    network_mode: host
    environment:
      - TZ=Europe/Kiev
    restart: unless-stopped
#    restart: on-failure
# 5437 внешний порт 
# 5432 внутри контейнера
       